# Generated by Django 6.1 on 2026-08-23 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], default='pending', max_length=20),
        ),
        migrations.RunSQL(
            "UPDATE blog_post SET status = 'approved'",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
