# Generated by Django 6.1 on 2026-09-02 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='private_content',
            field=models.TextField(blank=True, help_text="Content only visible to viewers with 'View Private Content' permission.", null=True, verbose_name='Private Content'),
        ),
        migrations.AddField(
            model_name='viewer',
            name='view_private',
            field=models.BooleanField(default=False, help_text='Grant this viewer access to private content.', verbose_name='View Private Content'),
        ),
    ]
