# Generated by Django 6.1 on 2026-08-25 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='template_file',
            field=models.CharField(help_text="Path in static/, e.g. 'games/2048.html'", max_length=200),
        ),
    ]
